version: "3.9"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: hunger-games-server
    container_name: hunger-games-server
    environment:
      - DATABASE_URL=postgresql://myuser:mysecretpassword@db:5432/mydatabase

  db:
    image: postgres
    container_name: hunger-games-db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
