version: "3.9"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_WS_PORT: 3001
        NEXT_PUBLIC_FEATURE_MANUAL_JOIN: true
    working_dir: /app
    ports:
      - 3000:3000
      - 3001:3001
    image: hunger-games-server
    container_name: hunger-games-server
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://myuser:mysecretpassword@db:5432/mydatabase
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
      - FEATURE_GAME_TIMEOUT=true

  db:
    image: postgres
    container_name: hunger-games-db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
