import "~/styles/globals.css";

import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/header";
import { ForceRedirect } from "./_components/force-redirect";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <TRPCReactProvider>
            <SignedIn></SignedIn>
            <ForceRedirect />
            <Header />
            <div>{children}</div>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
