import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/header";
import FightProvider from "./_feature/auto-join-game/fight-provider";
import { Toaster } from "~/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <TRPCReactProvider>
            <FightProvider>
              <Header />
              <div
                style={{
                  // 56px is the height of the header
                  height: "calc(100vh - 56px)",
                }}
              >
                {children}
              </div>
              <Toaster />
            </FightProvider>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
